language: python
python:
  - "3.7"

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - python setup.py develop
  - pip freeze

script:
  - python -m pytest --cov=India5G tests

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then coveralls || echo "failed"; fi
