language: python
python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - python setup.py develop
  - pip freeze

script:
  - python -m pytest --cov=india5g tests

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls || echo "failed"; fi
